import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Anek_Devanagari, Copse } from 'next/font/google';
import Nav from '@/components/Nav';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const anek = Anek_Devanagari({
  subsets: ['latin'],
  variable: '--main-font',
});

const copse = Copse({
  weight: ['400'],
  variable: '--normal-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anek.variable} ${copse.variable} antialiased min-h-screen`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
